version: '2'
services:
    striper-app:
        image: striper
        external_links:
            - striper-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=striper
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    striper-mongodb:
        extends:
            file: mongodb.yml
            service: striper-mongodb
